# Partimos de una imagen base de ubuntudonde instalaremos apache, lo configuraremos y arrancaremos.
FROM ubuntu
# ------Instalaciones------
RUN apt update && apt install -yq --no-install-recommends \
    apache2 \
    libapache2-mod-php7.2 \
    nano \
    curl \
    net-tools iputilils-ping
# ------Creacion de usuarios------
# Comandos interactivos (piden datos por terminal)
# Comandos por lotes (Datos los ponemos como parametros del comando)
RUN useradd -rm -d /home/adri -s /bin/bash adriana
RUN echo "adriana:1234" | chpasswd
RUN echo "Bienvenido adriana" > /home/adri/hello.txt

    # Debemos consultar el docker hub de ese contenedor/imagen para ver variables de entorno,
# directorio de trabajo, etc.
# Directorio de trabajo dentro del contenedor.
WORKDIR /usr/www/html
COPY ../src .
EXPOSE 80
CMD apacchectl -DFOREGROUND